using UnityEngine;

public class Projectile : MonoBehaviour
{
    public float lifetime = 3f;
    public int damage = 2;

    private playerStats playerStats;
    
    private void Start()
    {
        Destroy(gameObject, lifetime);

        // On r√©cup√®re le player automatiquement
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        if (player != null)
            playerStats = playerStats.Instance;
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        // üü° D√©g√¢ts au PLAYER si on touche un Enemy
        if (other.CompareTag("Enemy"))
        {
            MobStats mob = other.GetComponent<MobStats>();
            if (mob != null)
                mob.TakeDamage();
            Debug.Log("üî• Player hit by an enemy projectile!");
            if (playerStats != null)
                playerStats.health -= 2;
            Destroy(gameObject);
            return;
        }


        // üî¥ D√©g√¢ts aux Intrusi si on touche un Intrusi
        if (other.CompareTag("Intrusis"))
        {
            Debug.Log("üí• Intrusi hit!");
            MobStats mob = other.GetComponent<MobStats>();
            if (mob != null)
                mob.TakeDamage();

            Destroy(gameObject);
            return;
        }


        // ‚ùå Si on touche un obstacle, on d√©truit juste le projectile
        if (other.gameObject.layer == LayerMask.NameToLayer("Obstacle"))
        {
            Debug.Log("üß± Projectile destroyed by obstacle");
            Destroy(gameObject);
        }
    }
}
